server:
  port: 6003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/z_weixiao?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true